version: "3"
services:
  processor:
    entrypoint: ["node", "."]
    image: registry.oecloud.local/oecloudio-oe-async-service-processor:latest
    depends_on:
      - rabbitmq
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        delay: 60s
    environment:
      ROUTER_HOSTNAME: ${ROUTER}
      RABBITMQ_HOSTNAME: "rabbitmq"
      MAX_RETRY: "15"
      RETRIABLE_STATUS_CODES: "[503,500]"
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
    networks:
      - async-service_network
      - router_network

  rabbitmq:
    image: registry.oecloud.local/rabbitmq:3.6-management-alpine
    environment:
      VIRTUAL_HOST: "https://rabbitmq.oecloud.local,rabbitmq.oecloud.local"
      SERVICE_PORTS: "15672"
    networks:
      - async-service_network
      - router_network

  server:
    entrypoint: ["node", "."]
    image: registry.oecloud.local/oecloudio-oe-async-service-server:latest
    depends_on:
      - rabbitmq
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        delay: 60s
    environment:
      VIRTUAL_HOST: "https://${RETRY_SERVICE_NAME}.${DOMAIN_NAME},${RETRY_SERVICE_NAME}.${DOMAIN_NAME}"
      SERVICE_PORTS: "3000"
      FORCE_SSL: "true"
      ROUTER_HOSTNAME: ${ROUTER}
      RABBITMQ_HOSTNAME: "rabbitmq"
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
      RETRIABLE_STATUS_CODES: "[503,500]"
    networks:
      - async-service_network
      - router_network

networks:
  async-service_network:
  router_network:
    external: true
